# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuthFireBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuthFireBase
  pod 'Firebase'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'FirebaseAnalytics'
end
